name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - uses: actions/checkout@v3
      with:
        repository: 'itsmattkc/msvc420'
        path: msvc420

    - name: Restore cached DX5 SDK
      id: cache-dx5
      uses: actions/cache/restore@v3
      with:
        path: dx5sdk
        key: dx5sdk

    - name: Download DX5 SDK
      if: steps.cache-dx5.outputs.cache-hit != 'true'
      run: |
        cd dx5sdk
        curl -fLOSs https://archive.org/download/idx5sdk/idx5sdk.exe
        7z x .\idx5sdk.exe
        7z x .\DX5SDK.EXE

    - name: Cache DX5 SDK
      if: steps.cache-dx5.outputs.cache-hit != 'true'
      id: save-dx5
      uses: actions/cache/save@v3
      with:
        path: dx5sdk
        key: dx5sdk

    - name: Setup DX5 SDK
      run: |
        cd dx5sdk
        cd cdrom
        .\SETUP.EXE /s

    - name: Build
      shell: cmd
      run: |
        call .\msvc420\bin\VCVARS32.BAT x86
        mkdir Release
        .\msvc420\bin\NMAKE.EXE /f isle.mak CFG="ISLE - Win32 Release"

    - name: Summarize Accuracy
      shell: cmd
      run: |
        curl -fLOSs https://legoisland.org/download/ISLE.EXE
        curl -fLOSs https://legoisland.org/download/LEGO1.DLL
        pip install capstone
        pip install colorama
        python3 tools/reccmp/reccmp.py -S ISLEPROGRESS.SVG --svg-icon tools/reccmp/isle.png -H ISLEPROGRESS.HTML ISLE.EXE Release/ISLE.EXE Release/ISLE.PDB .
        python3 tools/reccmp/reccmp.py -S LEGO1PROGRESS.SVG -T 1929 --svg-icon tools/reccmp/lego1.png -H LEGO1PROGRESS.HTML LEGO1.DLL Release/LEGO1.DLL Release/LEGO1.PDB .
      
    - name: Upload Artifact
      uses: actions/upload-artifact@master
      with:
        name: Win32
        path: |
          Release
          ISLEPROGRESS.HTML
          LEGO1PROGRESS.HTML
          ISLEPROGRESS.SVG
          LEGO1PROGRESS.SVG

    - name: Upload Continuous Release
      shell: bash
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # Convert SVGs to PNG
        INKSCAPE_DIR=inkscape-1.2.2_2022-12-09_732a01da63-x64
        curl -fLOSs https://inkscape.org/gallery/item/37364/$INKSCAPE_DIR.7z
        7z x $INKSCAPE_DIR.7z
        $INKSCAPE_DIR/bin/inkscape -w 1024 ISLEPROGRESS.SVG -o ISLEPROGRESS.PNG
        $INKSCAPE_DIR/bin/inkscape -w 1024 LEGO1PROGRESS.SVG -o LEGO1PROGRESS.PNG

        curl -fLOSs https://raw.githubusercontent.com/probonopd/uploadtool/master/upload.sh
        ./upload.sh \
          Release/ISLE.EXE \
          Release/LEGO1.DLL \
          ISLEPROGRESS.HTML \
          ISLEPROGRESS.SVG \
          ISLEPROGRESS.PNG \
          LEGO1PROGRESS.HTML \
          LEGO1PROGRESS.PNG \
          LEGO1PROGRESS.SVG
